# Prep v1

Prepare clean EURUSD H1 data for feature engineering.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# file path
path = r"C:\Users\LENOVO\AlgoTrading_Research\statistical-range-detection\data\raw\EURUSD_H1_2022_2025_raw.csv"

# load dataset & column names
df = pd.read_csv(path, sep=",", header=None, encoding="utf-16", names=["date", "open", "high", "low", "close", "tick_volume", "spread"], parse_dates=["date"], index_col="date")

df.head()

                        open     high      low    close  tick_volume  spread
date
2022-10-25 00:00:00  0.98712  0.98752  0.98674  0.98705          452       0
2022-10-25 01:00:00  0.98701  0.98875  0.98700  0.98868         2464       0
2022-10-25 02:00:00  0.98868  0.98904  0.98836  0.98843         2428       0
2022-10-25 03:00:00  0.98843  0.98972  0.98787  0.98943         7115       0
2022-10-25 04:00:00  0.98943  0.98986  0.98773  0.98878         9177       0

In [3]:
df = df.sort_index()

df.head()

                        open     high      low    close  tick_volume  spread
date
2022-10-25 00:00:00  0.98712  0.98752  0.98674  0.98705          452       0
2022-10-25 01:00:00  0.98701  0.98875  0.98700  0.98868         2464       0
2022-10-25 02:00:00  0.98868  0.98904  0.98836  0.98843         2428       0
2022-10-25 03:00:00  0.98843  0.98972  0.98787  0.98943         7115       0
2022-10-25 04:00:00  0.98943  0.98986  0.98773  0.98878         9177       0

In [4]:
df.index.is_monotonic_increasing

True

In [5]:
df.index.duplicated().sum()

np.int64(0)

In [6]:
df["returns"] = df["close"].pct_change()

df.head()

,open,high,low,close,tick_volume,spread,returns
date,,,,,,,
2022-10-25 00:00:00,0.98712,0.98752,0.98674,0.98705,452,0,NaN
2022-10-25 01:00:00,0.98701,0.98875,0.98700,0.98868,2464,0,0.001651
2022-10-25 02:00:00,0.98868,0.98904,0.98836,0.98843,2428,0,-0.000253
2022-10-25 03:00:00,0.98843,0.98972,0.98787,0.98943,7115,0,0.001012
2022-10-25 04:00:00,0.98943,0.98986,0.98773,0.98878,9177,0,-0.000657

In [7]:
df["log_returns"] = np.log(df["close"] / df["close"].shift(1))

df.head()

,open,high,low,close,tick_volume,spread,returns,log_returns
date,,,,,,,,
2022-10-25 00:00:00,0.98712,0.98752,0.98674,0.98705,452,0,NaN,NaN
2022-10-25 01:00:00,0.98701,0.98875,0.98700,0.98868,2464,0,0.001651,0.001650
2022-10-25 02:00:00,0.98868,0.98904,0.98836,0.98843,2428,0,-0.000253,-0.000253
2022-10-25 03:00:00,0.98843,0.98972,0.98787,0.98943,7115,0,0.001012,0.001011
2022-10-25 04:00:00,0.98943,0.98986,0.98773,0.98878,9177,0,-0.000657,-0.000657

In [8]:
df.isnull().sum()

open           0
high           0
low            0
close          0
tick_volume    0
spread         0
returns        1
log_returns    1
dtype: int64

In [9]:
df = df.dropna()

df.head()

,open,high,low,close,tick_volume,spread,returns,log_returns
date,,,,,,,,
2022-10-25 01:00:00,0.98701,0.98875,0.98700,0.98868,2464,0,0.001651,0.001650
2022-10-25 02:00:00,0.98868,0.98904,0.98836,0.98843,2428,0,-0.000253,-0.000253
2022-10-25 03:00:00,0.98843,0.98972,0.98787,0.98943,7115,0,0.001012,0.001011
2022-10-25 04:00:00,0.98943,0.98986,0.98773,0.98878,9177,0,-0.000657,-0.000657
2022-10-25 05:00:00,0.98879,0.98898,0.98782,0.98846,5202,0,-0.000324,-0.000324

In [10]:
df.isnull().sum()

open           0
high           0
low            0
close          0
tick_volume    0
spread         0
returns        0
log_returns    0
dtype: int64

In [11]:
df["returns"].describe()

count    19026.000000
mean         0.000009
std          0.000990
min         -0.011096
25%         -0.000393
50%          0.000008
75%          0.000410
max          0.017398
Name: returns, dtype: float64

In [12]:
df.describe()

,open,high,low,close,tick_volume,spread,returns,log_returns
count,19026.000000,19026.000000,19026.000000,19026.000000,19026.000000,19026.0,19026.000000,19026.000000
mean,1.091302,1.092008,1.090616,1.091318,2972.713760,0.0,0.000009,0.000009
std,0.039095,0.039079,0.039110,0.039091,2955.265738,0.0,0.000990,0.000990
min,0.973960,0.975140,0.973020,0.973950,18.000000,0.0,-0.011096,-0.011158
25%,1.068300,1.068983,1.067620,1.068285,1239.000000,0.0,-0.000393,-0.000393
50%,1.085410,1.085920,1.084875,1.085410,2126.500000,0.0,0.000008,0.000008
75%,1.105240,1.105940,1.104570,1.105258,3603.000000,0.0,0.000410,0.000410
max,1.187080,1.191850,1.186590,1.187050,66526.000000,0.0,0.017398,0.017249

In [13]:
df.to_csv(r"C:\Users\LENOVO\AlgoTrading_Research\statistical-range-detection\data\processed\eurusd_h1_v1.csv")

In [14]:
test = pd.read_csv(r"C:\Users\LENOVO\AlgoTrading_Research\statistical-range-detection\data\processed\eurusd_h1_v1.csv")

test.head()

,date,open,high,low,close,tick_volume,spread,returns,log_returns
0,2022-10-25 01:00:00,0.98701,0.98875,0.98700,0.98868,2464,0,0.001651,0.001650
1,2022-10-25 02:00:00,0.98868,0.98904,0.98836,0.98843,2428,0,-0.000253,-0.000253
2,2022-10-25 03:00:00,0.98843,0.98972,0.98787,0.98943,7115,0,0.001012,0.001011
3,2022-10-25 04:00:00,0.98943,0.98986,0.98773,0.98878,9177,0,-0.000657,-0.000657
4,2022-10-25 05:00:00,0.98879,0.98898,0.98782,0.98846,5202,0,-0.000324,-0.000324